# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97e1bf6922fa7b791206cd3a6d2ecd48bcfd5f46e0d13d94e92a8037b784dc5afc3db7b85ceb4cd698ee1f65ad8903d02ee33fcfa8445be00954abcf86f6869a

test:
  secret_key_base: 94929c828cfb63b1912401d562fd5836e45657bbe9dc162caf281032f02ef88ad51c8eddc3403692f9144178e6a19112f1ffc80cde9cb38c64cec792b2659823

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
