# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(email: "a1@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a2@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a3@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a4@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a5@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a6@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a7@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a8@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a9@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a10@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a11@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a12@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a13@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a14@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a15@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a16@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a17@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a18@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a19@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a20@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a21@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a22@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a23@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a24@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a25@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a26@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a27@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a28@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a29@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a30@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a31@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a32@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a33@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a34@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a35@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a36@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a37@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a38@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a39@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a40@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a41@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a42@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a43@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a44@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a45@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a46@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a47@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a48@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a49@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a50@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a51@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a52@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a53@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a54@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a55@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a56@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a57@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a58@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a59@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a60@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a61@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a62@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a63@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a64@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a65@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a66@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a67@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a68@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a69@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a70@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a71@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a72@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a73@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a74@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a75@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a76@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a77@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a78@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a79@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a80@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a81@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a82@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a83@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a84@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a85@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a86@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a87@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a88@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a89@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a90@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a91@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a92@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a93@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a94@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a95@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a96@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a97@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a98@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a99@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "a100@gmail.com", password: "foobar20", password_confirmation: "foobar20", level: 0)
User.create(email: "admin@admin.com", password: "foobar20", password_confirmation: "foobar20", level: 1)
User.create(email: "verify@admin.com", password: "foobar20", password_confirmation: "foobar20", level: 2)

Stream.create(name: "BA English", GEN: 80, SC: 79, ST: 78, OBC_A: 77, OBC_B: 76)
Stream.create(name: "BA Sanskrit", GEN: 81, SC: 79, ST: 78, OBC_A: 75, OBC_B: 76)
Stream.create(name: "BA Hindi", GEN: 82, SC: 80, ST: 78, OBC_A: 77, OBC_B: 76)
Stream.create(name: "BA History", GEN: 80, SC: 79, ST: 78, OBC_A: 77, OBC_B: 76)
Stream.create(name: "BA Economics", GEN: 70, SC: 69, ST: 68, OBC_A: 66, OBC_B: 67)
Stream.create(name: "BSc Maths", GEN: 80, SC: 78, ST: 78, OBC_A: 77, OBC_B: 76)
Stream.create(name: "BA Physics", GEN: 81, SC: 79, ST: 78, OBC_A: 76, OBC_B: 75)
Stream.create(name: "BA Chemistry", GEN: 82, SC: 69, ST: 68, OBC_A: 67, OBC_B: 66)
Stream.create(name: "BA Zoology", GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56)
Stream.create(name: "BA Botany", GEN: 81, SC: 80, ST: 78, OBC_A: 77, OBC_B: 76)


Subject.create(name: "English")
Subject.create(name: "Hindi")
Subject.create(name: "Sanskrit")
Subject.create(name: "Physics")
Subject.create(name: "Mathematics")
Subject.create(name: "Chemistry")
Subject.create(name: "Biology")
Subject.create(name: "History")
Subject.create(name: "Geography")
Subject.create(name: "Political science")
Subject.create(name: "French")
Subject.create(name: "Environmental")
Subject.create(name: "Sports")
Subject.create(name: "Computer science")
Subject.create(name: "Economics")
Subject.create(name: "Statistics")
Subject.create(name: "Buisness study")


SubStrMap.create(stream_id: 1, subject_id: 1, GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56 )
SubStrMap.create(stream_id: 2, subject_id: 2, GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56 )
SubStrMap.create(stream_id: 2, subject_id: 3, GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56 )
SubStrMap.create(stream_id: 3, subject_id: 2, GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56 )
SubStrMap.create(stream_id: 4, subject_id: 9, GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56 )
SubStrMap.create(stream_id: 5, subject_id: 15, GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56 )
SubStrMap.create(stream_id: 5, subject_id: 16, GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56 )
SubStrMap.create(stream_id: 6, subject_id: 5, GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56 )
SubStrMap.create(stream_id: 7, subject_id: 4, GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56 )
SubStrMap.create(stream_id: 7, subject_id: 5, GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56 )
SubStrMap.create(stream_id: 8, subject_id: 4, GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56 )
SubStrMap.create(stream_id: 8, subject_id: 6, GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56 )
SubStrMap.create(stream_id: 9, subject_id: 6, GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56 )
SubStrMap.create(stream_id: 9, subject_id: 7, GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56 )
SubStrMap.create(stream_id: 10, subject_id: 7, GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56 )
SubStrMap.create(stream_id: 10, subject_id: 6, GEN: 70, SC: 59, ST: 58, OBC_A: 57, OBC_B: 56 )
